name: app_casynet
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.15.0 <3.0.0"

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  flutter_switch: ^0.3.2
  image_picker: ^0.8.4+11
  flutter_svg:
  get:
  font_awesome_flutter:
  dotted_border:
  flutter_datetime_picker:
  intl:
  flutter_slidable:
  dropdown_button2:

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^1.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/store/img_donhang.png
    - assets/store/img_money.png
    - assets/store/img_74.png
    - assets/store/ic_question_circle.png
    - assets/store/img_mask_group_14.png
    - assets/cart/img_mask_group_18.png
    - assets/cart/icon_payment1.png
    - assets/cart/icon_payment.png
    - assets/cart/ic_payment.png
    - assets/cart/icon_giaohang.png
    - assets/cart/img_sale.png
    - assets/cart/icon_minus2.png
    - assets/cart/icon_minus.png
    - assets/cart/img_rectangle.png
    - assets/cart/icon_coin.png
    - assets/cart/ic_gift.png
    - assets/cart/ic_check.png
    - assets/splash/path1483.svg
    - assets/splash/path1484.svg
    - assets/splash/logo-while.png
    - assets/splash/logo.png
    - assets/button_image_location.png
    - assets/arrow_down.svg
    - assets/splash/group_527.png
    - assets/splash/path1481.svg
    - assets/splash/path1482.svg
    - assets/home/icon_top_home.svg
    - assets/home/logo.svg
    - assets/home/dadangky.png
    - assets/home/icon_location.svg
    - assets/home/banner1.png
    - assets/home/flash_sale.png
    - assets/home/tichdiem.png
    - assets/home/khuyenmai.png
    - assets/home/free_ship.png
    - assets/home/category/chamsocxe.png
    - assets/home/category/dochoiphukien.png
    - assets/home/category/lopacquy.png
    - assets/home/category/suachuaxe.png
    - assets/home/category/ruaxethaydau.png
    - assets/home/category/bt_ruaxethaydau.svg
    - assets/home/category/bt_chamsocxe.svg
    - assets/home/category/bt_dochoiphukien.svg
    - assets/home/category/bt_lopacquy.svg
    - assets/home/category/bt_muabanxe.svg
    - assets/home/category/bt_suachuaxe.svg
    - assets/home/category/left_bottom.svg
    - assets/home/category/muabanxe.png
    - assets/home/store/icon_xemthem.svg
    - assets/home/store/cuahang1.png
    - assets/home/store/cuahang2.png
    - assets/home/store/icon_filter.svg
    - assets/home/store/icon_re2.png
    - assets/home/store/phone.svg
    - assets/home/book/image.png
    - assets/bottom_navi_icon/account.svg
    - assets/bottom_navi_icon/cart.svg
    - assets/bottom_navi_icon/home.svg
    - assets/bottom_navi_icon/noti.svg
    - assets/bottom_navi_icon/detail.svg
    - assets/account/fb.svg
    - assets/account/gg.svg
    - assets/account/zalo.svg
    - assets/account/image_user.png
    - assets/account/background.png
    - assets/account/right_background.png
    - assets/account/edit.svg
    - assets/background.svg
    - assets/background_2.svg
    - assets/notification/noti_1.png
    - assets/filter/image83.png
    - assets/detail_product/product_1.png
    - assets/detail_product/coin.svg
    - assets/detail_product/gift.svg
    - assets/detail_product/phone-volume.svg
    - assets/detail_product/cart.svg
    - assets/detail_product/cart2.svg
    - assets/detail_product/ic_perm_phone.svg
    - assets/detail_product/ic_alarm.svg
    - assets/detail_product/calendar-alt.svg
    - assets/detail_product/back_sale.svg
    - assets/detail_product/message.svg
    - assets/benefit/image.png
    - assets/detail_store/anhCuaHang.png
    - assets/detail_store/background.png
    - assets/detail_store/ower_store.png
    - assets/detail_store/gift.svg
    - assets/detail_store/right.svg
    - assets/detail_store/vote.png
    - assets/home/sale.svg
    - assets/home/rect_sale.svg
    - assets/Icon/icon_ttcuahang.png
    - assets/Icon/icon_thongbao.png
    - assets/Icon/icon_quatang.png
    - assets/Icon/icon_home.png
    - assets/Icon/icon_dashboard.png
    - assets/Icon/icon_tintuc.png
    - assets/Icon/icon_dvsp.png
    - assets/Icon/icon_doanhso.png
    - assets/Icon/icon_dung.png
    - assets/Icon/icon_dongho.png
    - assets/Icon/icon_butchi.png
    - assets/Icon/icon_date.png
    - assets/Icon/icon_dung2.png




  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
