List<Map<String, dynamic>>  stores =[
  {
  "id": 1,
  "name": "Gara ô tô vinaoto",
  "address": "Thanh Xuan, Hà Nội",
  "number" : "09988888",
  "image_url": "assets/home/store/cuahang1.png",
  "like" : 23,
  "comment" : 10,
  "quality" : 11,
  "distance" : 12,
  "category" : "car",
  },
  {
    "id": 2,
    "name": "Audi Việt Nam ",
    "address": "Nam Từ Liêm, Hà Nội",
    "number" : "09988888",
    "image_url": "assets/home/store/cuahang1.png",
    "like" : 23,
    "comment" : 14,
    "quality" : 13,
    "distance" : 11,
    "category" : "car",
  },
  {
    "id": 3,
    "name": "Gara ô tô vinaoto",
    "address": "435 Trần Khát Chân",
    "number" : "09988888",
    "image_url": "assets/home/store/cuahang1.png",
    "like" : 23,
    "comment" : 10,
    "quality" : 11,
    "distance" : 12,
    "category" : "car",
  },
  {
    "id": 4,
    "name": "Sửa xe Hòa Bình",
    "address": "6/6A Lê Lợi, Thị Trấn Hóc Môn",
    "number" : "09988888",
    "image_url": "assets/home/store/cuahang1.png",
    "like" : 22,
    "comment" : 10,
    "quality" : 11,
    "distance" : 12,
    "category" : "car",
  },
  {
    "id": 5,
    "name": "Sửa xe Đặng Rum",
    "address": "35/4A Ấp 5 Phan Văn Hớn, Xuân Thới Thượng",
    "number" : "09988888",
    "image_url": "assets/home/store/cuahang1.png",
    "like" : 11,
    "comment" : 10,
    "quality" : 11,
    "distance" : 12,
    "category" : "car",
  },
  {
    "id": 6,
    "name": "Sửa xe Phúc Long",
    "address": " 105/ 2D Phan Văn Hớn, Xuân Thới Thượng",
    "number" : "09988888",
    "image_url": "assets/home/store/cuahang1.png",
    "like" : 2,
    "comment" : 10,
    "quality" : 11,
    "distance" : 12,
    "category" : "car",
  }
];