// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBokJorOeMqZJrE0NTQShL3BSPHXwyNP4E',
    appId: '1:122983813069:android:8595b3dec985f91897be84',
    messagingSenderId: '122983813069',
    projectId: 'notifications-flutter-100cd',
    storageBucket: 'notifications-flutter-100cd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAtpBk5Ojykrd4NHAQVWovnA3cWNTHaEMM',
    appId: '1:122983813069:ios:3de5db8f747329fb97be84',
    messagingSenderId: '122983813069',
    projectId: 'notifications-flutter-100cd',
    storageBucket: 'notifications-flutter-100cd.appspot.com',
    iosClientId: '122983813069-gckdi85v9p20ct7o7a5u1r55ed3d98a2.apps.googleusercontent.com',
    iosBundleId: 'com.example.appCasynet',
  );
}
